server:
  port: 6600

spring:
  application:
    name: ideas-server
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://118.31.16.35:3306/ideas?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 118.31.16.35
    port: 6379
    password: 123456

mybatis:
  type-aliases-package: com.lll.ideas.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


